version: '3'
services:
  webapp:
    image: teste:latest
    networks:
      - common-network
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    networks:
      - common-network
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
networks:
  common-network:
    driver: bridge