name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            app
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install -r app/v1/src/environment_configs/requirements.txt
      - name: Test
        run: |
          echo "Assigning the app root directory path value to PYTHONPATH"
          export PYTHONPATH=$PWD/app
          
          echo "Running tests"
          pytest app/v1/test
