name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            app
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          echo "$PWD"
          echo "-----"
          ls
          pip install -r v1/src/environment_configs/requirements.txt
          echo "Dependencies installed."
      - name: Test
        run: |
          pytest v1/test